# conda env update -f environment.yml --prune
# conda env create -f environment.yml
# conda env remove --name master_venv
# conda activate master_venv
# conda deactivate

name: master_env
channels: 
  - conda-forge
  - defaults
  - anaconda
dependencies:

# libaries for scrapers
  - BeautifulSoup4==4.9.3
  - selenium==3.141.0
  - scrapy # ==2.5.0
  - PyPDF2
  - pdf2image
  - poppler # needed for pdf2image

# data handling
  - validators==0.18.2
  - pandas==1.2.4
  - thefuzz==0.19.0
  - regex==2021.11.10
  - nltk==3.6.5
  - scikit-learn
  - seaborn==0.11.2
  - regex
  - langdetect
  - translators

# machine learning
  - gensim
  - pytorch
  - torchvision
  - transformers==4.23.1
  - huggingface_hub==0.10.0 # needs to be updated after installing transformers, if not -> error
  - optuna==2.10.0
  - sentencepiece # for xlnet tokenizer

# visualisation
  - matplotlib
  - plotly
  - nbformat
  - wordcloud

# linting
  - flake8==4.0.1
  - pep8-naming==0.11.1
  - flake8-docstrings

# install with pip
# /Users/charlottjakob/opt/miniconda3/envs/master_venv/bin/pip install package
  - pip
  - pip:
    - scrapy-user-agents==0.1.1
    - scikit-multilearn

